### ISSUE TITLE
WRNs in log

### ISSUE THREAD

**Issue by ktrainn** [FilUnderscore/ImprovedHordes#12] opened 2023-07-01 00:15 UTC
So this one I noticed early game today, got some stuttering during this, then it seemed to straighten itself out...

`2023-06-30T18:29:26 2096.812 INF [DECO] write thread 1ms
2023-06-30T18:29:33 2104.018 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-875.37, 83.79, 1315.42)
2023-06-30T18:29:33 2104.216 WRN [Improved Hordes] [WorldHordeTracker] TrySpawnCluster(HordeCluster,WorldHorde,PlayerHordeGroup): Failed to spawn horde cluster, retrying.
2023-06-30T18:29:33 2104.216 WRN [Improved Hordes] [HordeDefinitionEntityGenerator] .ctor(ILoggerFactory,PlayerHordeGroup,HordeDefinition): No eligible 'wandering_animal_enemy' horde groups for player group [gamestage=2, biome=pine_forest]. Using placeholder entity class 'zombieSpider'.
2023-06-30T18:29:33 2104.217 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-875.37, 83.79, 1315.42)

...and so on for a bit...

2023-06-30T18:30:13 2144.000 WRN [Improved Hordes] [WorldHordeTracker] TrySpawnCluster(HordeCluster,WorldHorde,PlayerHordeGroup): Failed to spawn horde cluster, retrying.
2023-06-30T18:30:13 2144.001 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-875.37, 83.79, 1315.42)
2023-06-30T18:30:13 2144.218 WRN [Improved Hordes] [HordeDespawnRequest] TickExecute(Single): Tried to despawn horde entities but no entities were spawned.
2023-06-30T18:30:25 2155.901 INF VehicleManager saving 0 (0 + 0)
` until fixing itself

**Comment by FilUnderscore** [comment] 2023-07-01 12:54
Thanks for reporting this, seems to be related to nearby hordes failing to find a suitable spawnpoint. 

A good solution might be to add some sort of delay after failure to find a spawn, until the horde moves into a better position. This should reduce the console warning spam and stuttering caused by it.

**Comment by SylenThunder** [comment] 2023-07-03 01:01
Have the same issue on our server. Seems to work fine for a while and then it just starts spamming...

2023-07-02T17:57:17 4637.360 WRN [Improved Hordes] [WorldHordeTracker] TrySpawnCluster(HordeCluster,WorldHorde,PlayerHordeGroup): Failed to spawn horde cluster, retrying.
2023-07-02T17:57:17 4637.386 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-1946.33, 34.46, -2994.85)
2023-07-02T17:57:17 4637.597 WRN [Improved Hordes] [WorldHordeTracker] TrySpawnCluster(HordeCluster,WorldHorde,PlayerHordeGroup): Failed to spawn horde cluster, retrying.
2023-07-02T17:57:17 4637.637 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-1946.33, 34.46, -2994.85)
2023-07-02T17:57:17 4637.834 WRN [Improved Hordes] [WorldHordeTracker] TrySpawnCluster(HordeCluster,WorldHorde,PlayerHordeGroup): Failed to spawn horde cluster, retrying.
2023-07-02T17:57:17 4637.838 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-1946.33, 34.46, -2994.85)
2023-07-02T17:57:18 4638.035 INF 4562.747 SleeperVolume -271, 43, -2992: Spawning -269, 47, -2989 (-17, -187), group 'sleeperHordeStageGS58', class zombieNurse, count 24
2023-07-02T17:57:18 4638.070 WRN [Improved Hordes] [WorldHordeTracker] TrySpawnCluster(HordeCluster,WorldHorde,PlayerHordeGroup): Failed to spawn horde cluster, retrying.
2023-07-02T17:57:18 4638.088 WRN [Improved Hordes] [HordeClusterSpawnMainThreadRequest] TickExecute(Single): Bad spawn request for horde at (-1946.33, 34.46, -2994.85)

After it's been doing this for a little bit, we almost get zero zed spawns in the world. The exception seems to be a rare biome spawn, and POI spawns.

**Comment by FilUnderscore** [comment] 2023-07-03 10:33
> After it's been doing this for a little bit, we almost get zero zed spawns in the world. The exception seems to be a rare biome spawn, and POI spawns.

Interesting lead, could this also be related to the infinite spawning bug that people are reporting as well.

**Comment by FilUnderscore** [comment] 2023-07-03 16:05
Update: I've managed to fix the spam by reworking the horde spawning system for next update. I'll update this issue when the update has been released.

**Comment by FilUnderscore** [comment] 2023-07-04 16:17
This has been fixed in 2.0.0-beta.1.

> "Failed to spawn horde cluster" and "Bad spawn location at" warnings fixed with the spawning system improvements.

> Random cases of horde entity group generation failing and using the placeholder zombieSpider entity class. 

Please re-open this issue if it still occurs after updating.

**Closed as completed by FilUnderscore** 2023-07-04 16:17 UTC
Labels: bug, experimental
