### ISSUE TITLE
Sleeper zombie horde doesnt wake up

### ISSUE THREAD

**Issue by xxsogramboxx** [FilUnderscore/ImprovedHordes#10] opened 2023-06-18 16:04 UTC
I have 
IH-BiggerHordesAddon
IH-NoScreamerScoutAddon
IH-RandomHordesAddon
IMPROVED HORDES mods loaded. 
The sleeper horde doesn't wake up when I start hitting them. Are they supposed to wake up? They are just free xp as they look around but stay in the sitting animation. 
Message me on discord if you want to contact me 500 Magnum #9239

**Comment by xxsogramboxx** [comment] 2023-06-19 04:49
Also now there's hordes spawning one after the other.  Hahaha, I can't find where the hordes per day is in the mod files

**Comment by FilUnderscore** [comment] 2023-06-19 04:59
Thanks for reporting this.

> I have
> IH-BiggerHordesAddon
> IH-NoScreamerScoutAddon
> IH-RandomHordesAddon
> IMPROVED HORDES mods loaded.
> The sleeper horde doesn't wake up when I start hitting them. Are they supposed to wake up? They are just free xp as they look around but stay in the sitting animation.
> Message me on discord if you want to contact me 500 Magnum #9239

Yes, sleeper hordes are supposed to wake up. I noticed they do wake up if you generate enough heat near them, but do not if you come close to them. I’m looking into this and expect a potential fix in the next update. I only expect to push urgent updates on game breaking bugs like errors, so this may be a couple of days.

> Also now there's hordes spawning one after the other. Hahaha, I can't find where the hordes per day is in the mod files

This is not a bug, rather the new base functionality of the mod where hordes can now hear things like gunshots and check it out. There is a set number of hordes in the world at one time depending on world size, and respawns are limited at the moment to weekly (however hordes are not currently saved so they will respawn every time you reopen the game).

If you take down the hordes, they shouldn’t come after you for some time unless other hordes happen to wander by. Hordes no longer spawn randomly and are instead roaming the world as you are exploring/setting up base.

**Comment by FilUnderscore** [comment] 2023-06-19 15:16
Issue has been resolved in the latest release, [2.0.0-alpha.3](https://github.com/FilUnderscore/ImprovedHordes/releases/tag/2.0.0-alpha.3).

**Fixed: Sleeping hordes do not awaken if you get close. Now sleeping zombies wake up if you get within 15m.**

**Closed as completed by FilUnderscore** 2023-06-19 15:16 UTC
Labels: bug, experimental

**Comment by xxsogramboxx** [comment] 2023-06-19 19:47
Is there a way to lower the number roaming? Is it horde threads?

**Comment by FilUnderscore** [comment] 2023-06-20 03:14
> Is there a way to lower the number roaming? Is it horde threads?

You’ll want to lower max world density, as that controls how densely populated the world is with hordes.

 Max horde density controls how dense each individual horde is, so lowering that will decrease the number of zombies in a horde.
